### ISSUE TITLE
Multiple configurations

### ISSUE THREAD

**Issue by AntoineLemaire** [lightSAML/SymfonyBridgeBundle#26]
Hello there,

I have a multi-domains website (with [jms/i18n-routing-bundle](https://github.com/schmittjoh/JMSI18nRoutingBundle))
It allow me to have a list of hosts & locales but for the same application.

```
    locales: [en, de]
    hosts:
        en: foo.com
        de: foo.de
```

Until now, I had configure lightSAML only for one domain, because I needed only on it. 

So my `entity_id` is & my idp files are only related to `foo.com`

But now I'd like to use it for severals domain, but with different configuration per locale/host. So have a different `entity_id` for `foo.de` than `foo.com`, and same for idp metadata files.

Do you think it's possible?
