### ISSUE TITLE
Using Old SAML address with the new one

### ISSUE THREAD

**Issue by bMahadevan** [lightSAML/SymfonyBridgeBundle#7]
@tmilos 

Is that possible to have the old SAML urls with your new one? We have the old urls like /saml/sp/acs.
The previous URL has been changed to /saml/login_check now. Is there any way to have the old URL in parallel too in your SAML 2.0 bundle? If so please share an example.

Thank you?

**Comment by tmilos** [comment]
Sure, you can change login URLs, by symfony's default they are ``/saml/login`` and ``/saml/login_check``, and I didn't changed them for the bundle, but you can override default firewall config in your security.yml. Take a look at [step 11 of getting started](http://www.lightsaml.com/SP-Bundle/Getting-started/#step-11-configure-security). You can do

```yml
# app/config/security.yml
security:
    firewalls:
        main:
            light_saml_sp:
                provider: db_provider
                user_creator: user_creator
                login_path: /saml/sp/login
                check_path: /saml/sp/acs  # OVERRIDE DEFAULT VALUE AND CHANGE AS YOU NEED
            logout:
                path: /logout
            anonymous: ~
```

Theoretically they could work together, the old and the new version of lightsaml, but I haven't tried. But is there any particular reason you would like to do that? Not sure what you would achieve. I would rather not recommend it.
