### ISSUE TITLE
Service definitions not compatible with Symfony 2.3

### ISSUE THREAD

**Issue by bartvw** [lightSAML/SymfonyBridgeBundle#8]
Several services have a 'factory' parameter, which requires Symfony 2.6. 

Example in credential.yml:

```yaml
lightsaml.credential.credential_store:
        class: LightSaml\Store\Credential\CompositeCredentialStore
        factory: [LightSaml\SymfonyBridgeBundle\Factory\CredentialStoreFactory, build]
        arguments:
            - "@lightsaml.party.idp_entity_descriptor_store"
            - "@lightsaml.party.sp_entity_descriptor_store"
            - "%lightsaml.own.entity_id%"
            - "@lightsaml.own.credential_store"
            - []
```

In Symfony 2.3 this should be `factory_class` or `factory_service`, and `factory_method`. 
I noticed this has already been fixed for some services (by dynamically creating the service definitions from the Extension class) and the same should probably be done for these services.
